### ISSUE TITLE
SDK currently unavailable due to Jitpack being down. 

### ISSUE THREAD

**Issue by kevincmojo** [socure-inc/socure-docv-sdk-android#16]
No status update from the jitpack team either. Would it be possible to host on separate repo as well considering jitpack has been unstable at times?

https://github.com/jitpack/jitpack.io/issues/5337

**Comment by buraksocure** [comment]
Thanks for your reaching out! @kevincmojo 

Yes we are experiencing more outages on JitPack these days. 

That's why, we are working on to create our in-house server for distributing our SDKs as you suggested.  Please subscribe from here to get an updates -> https://developer.socure.com/release-notes/subscribe
